export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const ADD_NEW_DECK = 'ADD_NEW_DECK';

export const TOGGLE_ANSWER = 'TOGGLE_ANSWER';
export const CORRECT_ANSWER = 'CORRECT_ANSWER';
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER';
export const LAST_CORRECT_ANSWER = 'LAST_CORRECT_ANSWER';
export const LAST_INCORRECT_ANSWER = 'LAST_INCORRECT_ANSWER';
export const RESTART_QUIZ = 'RESTART_QUIZ';