export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const ADD_NEW_DECK = 'ADD_NEW_DECK';

export const CORRECT_ANSWER = 'CORRECT_ANSWER';
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER';
export const MANAGE_QUIZ_END_INC_SCORE = 'MANAGE_QUIZ_END_INC_SCORE';
export const MANAGE_QUIZ_END_DEC_SCORE = 'MANAGE_QUIZ_END_DEC_SCORE';
export const RESET_QUIZ = 'RESET_QUIZ';
export const TOGGLE_ANSWER = 'TOGGLE_ANSWER';